version: "3.1"
services:
  kheopssecuretrial:
    image: osirixfoundation/kheops-secure-trial:demo
    container_name: kheopssecuretrial
    env_file: docker-compose.env
    restart: always
    secrets:
      - institutions.yml

secrets:
  institutions.yml:
    file: secrets/institutions.yml

networks:
  default:
    external:
      name: kheops_kheops_network
